[package]
name = "AdventOfCode2019"
version = "0.1.0"
authors = ["GrumpyMetalGuy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.4"
text_io = "0.1"
permutohedron = "0.2"
num="0.2"
slice-deque="0.3"
