[package]
name = "AdventOfCode2019"
version = "0.1.0"
authors = ["GrumpyMetalGuy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-matrix = "0.1"